services:
  # 1. The Node.js App
  nodejs-app:
    image: otel-poc-nodejs-app:latest
    environment:
      - OTEL_SERVICE_NAME=node-poc-service
      - NODE_OPTIONS=--import ./instrumentation.js
    ports:
      - "14400:8080"
    depends_on:
      - otel-collector
    networks: [otel-poc-network]

  # 2. OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    networks: [otel-poc-network]

  # 3. Prometheus (Metrics)
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks: [otel-poc-network]

  # 4. Loki (Logs)
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks: [otel-poc-network]

  # 5. Tempo (Traces)
  # tempo:
  #   image: grafana/tempo:latest
  #   command: ["-config.file=/etc/tempo.yaml"]
  #   user: "0"
  #   volumes:
  #     - ./tempo.yaml:/etc/tempo.yaml
  #   ports:
  #     - "3200:3200"
  #     - "5317:4317"
  #   networks: [otel-poc-network]

  # 6. Grafana (Dashboard)
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3001:3000"
    networks: [otel-poc-network]

networks:
  otel-poc-network:
    external: true
